import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

type QuestionCardProps = {
  question: string;
};

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["question.get-all"]);

  if (isLoading || !data) return <div>Cargando...</div>;

  return (
    <>
      <Head>
        <title>Testing Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          <span className="text-purple-300">Polls</span> App
        </h1>
        <p className="text-2xl text-gray-700">Historial de preguntas:</p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          {data.map((q) => (
            <QuestionCard key={q.id} question={q.question} />
          ))}
        </div>
      </main>
    </>
  );
};

const QuestionCard = ({ question }: QuestionCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-violet-500 cursor-pointer">{question}</h2>
    </section>
  );
};

export default Home;
